### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by fatimazaheer** [ericjgagnon/wickedpicker#4]
Wicked picker is not showing up and down arrows

**Comment by ericjgagnon** [comment]
T'his issue could be caused by not including the fonts directory and/or changing the up and down selectors to ones of your choosing.  That being said, if you do choose to use your own icon fonts make sure that the selectors you are using have the the before pseudo element on them and are set up to use your icon fonts.  If you need an example you can look at the wickedpicker.css in the stylesheets directory.

**Comment by ghost** [comment]
Hi Eric, I am facing the same issue in my .Net Core MVC project. I have referred the wickedpicker.js and stylesheets to my page. but I don't know how to add the fonts file to my project. Could you please help me on how to apply/render the fonts?
